# Generated by Django 3.2.6 on 2021-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
