# Generated by Django 3.2.6 on 2021-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
